apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-sa
  namespace: diploe2-cevc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-eventlistener-binding
  namespace: diploe2-cevc
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-sa
    namespace: diploe2-cevc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles 
