apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: echo-task
spec:
  params:
    - name: message
      type: string
      default: "Hello World!"
  steps:
    - name: echo
      image: busybox
      script: |
        #!/bin/sh
        echo $(params.message) 
