apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: update-deployment-image-
  namespace: diploe2-cevc
spec:
  serviceAccountName: tekton-sa
  taskRef:
    name: kubernetes-actions
  params:
    - name: script
      value: |
        kubectl patch deployment $1 --patch='{"spec":{"template":{"spec":{
          "containers":[{
            "name": "'$1'",
            "image": "'$2'"
          }]
        }}}}'
    - name: args
      value:
        - cinerank
        - docker.io/cesarevc/cinerank-app:V2.1
